"use client";
import AddTask from "@/components/add-task/add-task.component";
import TaskList from "@/components/tasks-list/tasks-list.component";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ToDo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TaskList />
        <AddTask />
      </body>
    </html>
  );
}
